# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TableViewAuto' do
pod 'Masonry'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3'
end

target 'TableViewAutoTests' do

end

